import os
import sys
import tempfile
import json
import pytest
from unittest.mock import patch, MagicMock
import subprocess

# Add scripts directory to path to allow import
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "scripts")))

import spawn_auditor

def test_spawn_auditor_missing_channel(capsys):
    # Missing required argument will cause argparse to exit with code 2
    with patch.object(sys, "argv", ["spawn_auditor.py", "--enable-exec-from-workspace", "--prd-file", "dummy.md", "--workdir", "."]):
        with pytest.raises(SystemExit) as e:
            spawn_auditor.main()
        
        assert e.value.code == 2

@patch("subprocess.run")
def test_spawn_auditor_invalid_channel_handshake_fail(mock_run, capsys):
    # Simulate a failed handshake from the openclaw cli
    mock_run.return_value.returncode = 1
    mock_run.return_value.stdout = ""
    mock_run.return_value.stderr = "Invalid channel format"
    
    os.environ["SDLC_TEST_MODE"] = "false"
    with patch.object(sys, "argv", ["spawn_auditor.py", "--enable-exec-from-workspace", "--prd-file", "dummy.md", "--workdir", ".", "--channel", "invalid_format"]):
        with pytest.raises(SystemExit) as e:
            spawn_auditor.main()
        
        assert e.value.code == 1
        captured = capsys.readouterr()
        assert "Invalid notification channel format or failed handshake." in captured.out

def test_spawn_auditor_guardrail(capsys):
    with patch.object(sys, "argv", ["spawn_auditor.py", "--prd-file", "dummy.md", "--workdir", ".", "--channel", "test_channel"]):
        with pytest.raises(SystemExit) as e:
            spawn_auditor.main()
        
        assert e.value.code == 1
        captured = capsys.readouterr()
        assert "Startup validation failed" in captured.out

@patch("agent_driver.notify_channel")
def test_spawn_auditor_valid_channel_success(mock_notify, capsys):
    with tempfile.NamedTemporaryFile(suffix=".md", delete=False) as f:
        f.write(b"1. Context & Problem\n2. Requirements & User Stories\n3. Architecture & Technical Strategy\n4. Acceptance Criteria\n5. Overall Test Strategy\n6. Framework Modifications\n7. Hardcoded Content")
        prd_file = f.name
        
    os.environ["SDLC_TEST_MODE"] = "true"
    os.environ["MOCK_AUDIT_RESULT"] = "APPROVE"
    
    with patch.object(sys, "argv", ["spawn_auditor.py", "--enable-exec-from-workspace", "--prd-file", prd_file, "--workdir", ".", "--channel", "test_channel"]):
        spawn_auditor.main()
        
    captured = capsys.readouterr()
    assert "[ACTION REQUIRED FOR MANAGER] The Auditor APPROVED the PRD." in captured.out
    
    mock_notify.assert_any_call("test_channel", "Auditor APPROVED the PRD.", "auditor_approved", {"prd_file": prd_file})
    os.remove(prd_file)

@patch("agent_driver.notify_channel")
def test_spawn_auditor_valid_channel_reject(mock_notify, capsys):
    with tempfile.NamedTemporaryFile(suffix=".md", delete=False) as f:
        f.write(b"1. Context & Problem\n2. Requirements & User Stories\n3. Architecture & Technical Strategy\n4. Acceptance Criteria\n5. Overall Test Strategy\n6. Framework Modifications\n7. Hardcoded Content")
        prd_file = f.name
        
    os.environ["SDLC_TEST_MODE"] = "true"
    os.environ["MOCK_AUDIT_RESULT"] = "REJECT"
    
    with patch.object(sys, "argv", ["spawn_auditor.py", "--enable-exec-from-workspace", "--prd-file", prd_file, "--workdir", ".", "--channel", "test_channel"]):
        spawn_auditor.main()
        
    captured = capsys.readouterr()
    assert "[ACTION REQUIRED FOR MANAGER] The Auditor REJECTED the PRD." in captured.out
    
    mock_notify.assert_any_call("test_channel", "Auditor REJECTED the PRD.", "auditor_rejected", {"prd_file": prd_file})
    os.remove(prd_file)

@patch("agent_driver.notify_channel")
def test_auditor_notifies_on_missing_sections(mock_notify, capsys):
    with tempfile.NamedTemporaryFile(suffix=".md", delete=False) as f:
        # Malformed PRD: missing all mandatory sections
        f.write(b"This is a malformed PRD without any sections.")
        prd_file = f.name
        
    os.environ["SDLC_TEST_MODE"] = "true"
    
    with patch.object(sys, "argv", ["spawn_auditor.py", "--enable-exec-from-workspace", "--prd-file", prd_file, "--workdir", ".", "--channel", "test_channel"]):
        with pytest.raises(SystemExit) as e:
            spawn_auditor.main()
        
        # Should exit with code 0 per spawn_auditor logic
        assert e.value.code == 0
        
    captured = capsys.readouterr()
    expected_msg = "REJECTED: PRD structure does not match the mandatory template. Missing sections: 1. Context & Problem, 2. Requirements & User Stories, 3. Architecture & Technical Strategy, 4. Acceptance Criteria, 5. Overall Test Strategy, 6. Framework Modifications. DO NOT overwrite the template generated by init_prd.py with raw write tools."
    
    assert expected_msg in captured.out
    mock_notify.assert_called_once_with("test_channel", expected_msg, "auditor_rejected", {"prd_file": prd_file})
    
    os.remove(prd_file)

def test_prd_template_contains_section_7():
    template_path = os.path.join(os.path.dirname(__file__), "..", "skills", "pm-skill", "TEMPLATES", "PRD.md.template")
    if not os.path.exists(template_path):
        template_path = "/root/.openclaw/workspace/projects/docs/TEMPLATES/PRD.md.template"
        
    with open(template_path, "r") as f:
        content = f.read()
        
    assert "7. Hardcoded Content (硬编码内容)" in content
    assert "Anti-Hallucination Policy (防幻觉策略)" in content
    # Assert it is at the very end
    # Because of possible newlines, we strip the content and check if it ends with the block
    assert content.strip().endswith("```")
