#!/usr/bin/env python3
import argparse
import os
import sys
import uuid
import time

# Dynamic module resolution for monorepo development vs production deployment
current_dir = os.path.dirname(os.path.abspath(__file__))
import sys
sys.path.insert(0, current_dir)
import agent_driver
import config
from agent_driver import invoke_agent, build_prompt

def main():
    parser = argparse.ArgumentParser(description="Spawn an Auditor agent.")
    parser.add_argument("--prd-file", required=True, help="Path to the PRD file")
    parser.add_argument("--workdir", required=True, help="Working directory lock")
    parser.add_argument("--channel", required=True, help="Notification channel")
    parser.add_argument("--enable-exec-from-workspace", action="store_true", help="Bypass the workspace path check")
    parser.add_argument("--engine", choices=["openclaw", "gemini"], default=os.environ.get("LLM_DRIVER", config.DEFAULT_LLM_ENGINE), help=f"Execution engine to use for the agent driver (default: {config.DEFAULT_LLM_ENGINE})")
    parser.add_argument("--model", default=os.environ.get("SDLC_MODEL", config.DEFAULT_GEMINI_MODEL), help=f"Model to use when --engine is gemini (default: {config.DEFAULT_GEMINI_MODEL})")
    
    args = parser.parse_args()
    
    from handoff_prompter import HandoffPrompter
    if not args.enable_exec_from_workspace and not sys.argv[0].startswith(os.path.expanduser("~/.openclaw")):
        print(HandoffPrompter.get_prompt("startup_validation_failed"))
        sys.exit(1)
    
    if isinstance(args.engine, str) and args.engine != os.environ.get("LLM_DRIVER"):
        os.environ["LLM_DRIVER"] = args.engine
    if isinstance(args.model, str) and args.model != os.environ.get("SDLC_MODEL"):
        os.environ["SDLC_MODEL"] = args.model
    
    # Ignition Handshake
    cmd_handshake = ["openclaw", "message", "send"]
    if ":" in args.channel:
        parts = args.channel.split(":")
        if len(parts) >= 2:
            cmd_handshake.extend(["--channel", parts[0]])
            cmd_handshake.extend(["-t", ":".join(parts[1:])])
    else:
        cmd_handshake.extend(["-t", args.channel])
    
    import subprocess
    from agent_driver import notify_channel
    
    import shlex
    full_cmd = shlex.join([sys.executable] + sys.argv)
    
    msg = "Auditor Ignition: Starting audit..."
    cmd_handshake.extend(["-m", msg])
    
    if os.environ.get("SDLC_TEST_MODE") != "true":
        res = subprocess.run(cmd_handshake, capture_output=True, text=True)
        if res.returncode != 0:
            print(f"[FATAL_STARTUP]\n[ACTION REQUIRED FOR MANAGER]\nInvalid notification channel format or failed handshake. You MUST provide a valid OpenClaw channel string (e.g., `slack:CXXXXXX`) and ensure the gateway is running.")
            sys.exit(1)
            
    notify_channel(args.channel, "Auditor Ignition: Starting audit...", "auditor_start", {"prd_file": args.prd_file, "command": full_cmd})

    workdir = os.path.abspath(args.workdir)
    os.chdir(workdir)

    prd_file_abs = os.path.abspath(args.prd_file)
    if not os.path.exists(prd_file_abs):
        print(f"Error: PRD file not found: {prd_file_abs}")
        sys.exit(1)
        
    with open(prd_file_abs, "r") as f:
        prd_content = f.read()

    # Strict Template Validation
    required_sections = ["1. Context & Problem", "2. Requirements & User Stories", "3. Architecture & Technical Strategy", "4. Acceptance Criteria", "5. Overall Test Strategy", "6. Framework Modifications"]
    missing_sections = []
    for section in required_sections:
        if section not in prd_content:
            missing_sections.append(section)
            
    if missing_sections:
        error_msg = f"REJECTED: PRD structure does not match the mandatory template. Missing sections: {', '.join(missing_sections)}. DO NOT overwrite the template generated by init_prd.py with raw write tools."
        print(error_msg)
        agent_driver.notify_channel(args.channel, error_msg, "auditor_rejected", {"prd_file": args.prd_file})
        sys.exit(0)
        
    # Anti-Hallucination String Policy
    # Simple check: If PRD is missing section 7 but might need it, we reject. 
    # For now, we strictly require Section 7 if it's a standard PRD.
    if "7. Hardcoded Content" not in prd_content and "7. HARDCODED CONTENT" not in prd_content:
        print("REJECTED: The PRD mentions specific text/messages but fails to list them in 'Section 7. Hardcoded Content'. Ensure Coder has no room for hallucination.")
        sys.exit(0)

    SDLC_ROOT = os.path.dirname(current_dir)
    task_string = build_prompt("auditor",
        workdir=workdir,
        prd_file=prd_file_abs,
        base_dir=SDLC_ROOT
    )
    


    test_mode = os.environ.get("SDLC_TEST_MODE", "").lower() == "true"
    if test_mode:
        run_dir = os.environ.get("SDLC_RUN_DIR", ".")
        os.makedirs(os.path.join(run_dir, "tests"), exist_ok=True)
        with open(os.path.join(run_dir, "tests", "auditor_task_string.log"), "w") as f:
            f.write(task_string)
        if "REJECT" in os.environ.get("MOCK_AUDIT_RESULT", ""):
            output = '{"status": "REJECTED", "comments": "Mock rejected"}'
        else:
            output = '{"status": "APPROVED", "comments": "Mock approved"}'
        print(output)
    else:
        print(f"🚀 Launching Agentic PRD Auditor on {args.prd_file}...")
        session_id = f"prd_auditor_{int(time.time())}"
        
        from utils_api_key import get_api_keys_from_config, assign_gemini_api_key
        config_path = os.path.join(SDLC_ROOT, "config", "sdlc_config.json")
        gemini_api_keys = get_api_keys_from_config(config_path)
        if gemini_api_keys:
            state_file_path = os.path.join(os.path.abspath(args.workdir), ".sdlc_runs", ".session_keys.json")
            assigned_key = assign_gemini_api_key(session_id, gemini_api_keys, state_file_path)
            if assigned_key:
                os.environ["GEMINI_API_KEY"] = assigned_key

        result = invoke_agent(task_string, session_key=session_id, role="auditor")
        output = result.stdout

    status = "UNKNOWN"
    if '{"status": "APPROVED"' in output or '"status":"APPROVED"' in output or '"status": "APPROVED"' in output:
        status = "APPROVED"
    elif '{"status": "REJECTED"' in output or '"status":"REJECTED"' in output or '"status": "REJECTED"' in output:
        status = "REJECTED"

    import json
    try:
        # Try to parse exact json
        import re
        json_match = re.search(r'```json\s*(\{.*?\})\s*```', output, re.DOTALL)
        if not json_match:
            json_match = re.search(r'(\{.*?\})', output, re.DOTALL)
        if json_match:
            data = json.loads(json_match.group(1).strip())
            status = data.get("status", status)
    except Exception:
        pass

    if status == "APPROVED":
        agent_driver.notify_channel(args.channel, "Auditor APPROVED the PRD.", "auditor_approved", {"prd_file": args.prd_file})
        print("[ACTION REQUIRED FOR MANAGER] The Auditor APPROVED the PRD. Notify the Boss of the successful audit, then you MUST immediately halt all further operations and WAIT for explicit authorization to deploy.")
        sys.exit(0)
    else:
        agent_driver.notify_channel(args.channel, "Auditor REJECTED the PRD.", "auditor_rejected", {"prd_file": args.prd_file})
        print("[ACTION REQUIRED FOR MANAGER] The Auditor REJECTED the PRD. Report the rejection reasons to the Boss, then you MUST immediately halt all further operations and WAIT for explicit instructions.")
        sys.exit(0) # Boss Mandate: Prevent LLM YOLO retry by returning success code

if __name__ == "__main__":
    main()
